### ISSUE TITLE
No config file founded.

### ISSUE THREAD

**Issue by Estebiu** [janbuchar/rorqual#21]
Installed from the AUR, but there doesn't seem to be any default config file to customize.

**Comment by janbuchar** [comment]
Hi @Estebiu, you're right, there is currently none. You need to edit `~/.config/rorqual/config.toml` and insert something like this:

```toml
[subsonic]
user = "yourusername"
url = "http://the-server:4533"
# either this...
password_command = "some --command --to --get --password"
# or simply just
password = "your-password-in-plain-text"

[prefetching]
audio_cache_size = "4GB"  # adjust this as you see fit
```

Eventually, I'd like to implement some interactive configuration - if no config is found, the TUI will prompt you and create it for you.
